config/routes.rb
YAFU::Application.routes.draw do
  devise_for :users
  get 'admin' => 'admin#index'
  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :scrubs

  root 'sessions#new'

  

end

app/models/scrub.rb
class Scrub < ActiveRecord::Base
	belongs_to :user 
	validates :name, presence: true

	def self.latest
		Scrub.order(:updated_at).last
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :scrubs, dependent: :destroy
	validates :login, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true
	validates :name, presence: true
	validates :password_digest, presence: true
	has_secure_password	
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @users_count = User.count
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scrubs_controller.rb
class ScrubsController < ApplicationController
  before_action :set_scrub, only: [:show, :edit, :update, :destroy]
  # before_filter :authenticate_user!

  # GET /scrubs
  # GET /scrubs.json
  def index
    # @scrubs = Scrub.all
    @scrubs = Scrub.find_by(user_id: session[:user_id])
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    puts "session[:user_id] = #{session[:user_id]}"
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  end

  # GET /scrubs/1
  # GET /scrubs/1.json
  def show
  end

  # GET /scrubs/new
  def new
    @scrub = Scrub.new
  end

  # GET /scrubs/1/edit
  def edit
  end

  # POST /scrubs
  # POST /scrubs.json
  def create
    @scrub = Scrub.new(scrub_params)

    respond_to do |format|
      if @scrub.save
        format.html { redirect_to @scrub, notice: 'Scrub was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scrub }
      else
        format.html { render action: 'new' }
        format.json { render json: @scrub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scrubs/1
  # PATCH/PUT /scrubs/1.json
  def update
    respond_to do |format|
      if @scrub.update(scrub_params)
        format.html { redirect_to @scrub, notice: 'Scrub was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scrub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrubs/1
  # DELETE /scrubs/1.json
  def destroy
    @scrub.destroy
    respond_to do |format|
      format.html { redirect_to scrubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scrub
      @scrub = Scrub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrub_params
      params.require(:scrub).permit(:name, :file_type, :size)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	user = User.find_by(login: params[:login])
	user ||= User.find_by(email: params[:login])
	if user && user.authenticate(params[:password])
		session[:user_id] = user.id
		@user_id = user
		if user.login == 'God'
			redirect_to admin_url
		else
			redirect_to scrubs_url
		end
	else
		redirect_to login_url, alert: "Invalid user/password combinations"
	end	
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: "You logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User #{@user.login} was successfully created." }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User #{@user.login} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :password, :password_confirmation, :email, :name, :lastname, :d_birth)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scrubs_helper.rb
module ScrubsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome Admin!</h1>
Now <%= Time.now%>
<br>
We have <%=@users_count%> users.
<hr>
<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>D birth</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.d_birth %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YAFU</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
	<div id="banner">
		<a href=/><%= image_tag("logo.png") %></a>
		<%= @page_title || "Yet Another File Uploader" %>
	</div>
	<div class="account_link">
		<h3><a href=/users>Account</a>
		<a href="logout_path">Logout</a></h3>
	</div>
	<div id="columns">
		<div id="side">
			<ul>
				<li><a href="http://www....">Home</a></li>
				<li><a href="http://www..../faq">Questions</a></li>
				<li><a href="http://www..../news">News</a></li>
				<li><a href="http://www..../contact">Contact</a></li>
			</ul>
		</div>
	<div id="main">
			<%= yield %>

			<%= render 'layouts/user_widget' %>
			</div>
			</div>

</body>
</html>

app/views/scrubs/_form.html.erb
<%= form_for(@scrub) do |f| %>
  <% if @scrub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scrub.errors.count, "error") %> prohibited this scrub from being saved:</h2>

      <ul>
      <% @scrub.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file_type %><br>
    <%= f.text_field :file_type %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scrubs/edit.html.erb
<h1>Editing scrub</h1>

<%= render 'form' %>

<%= link_to 'Show', @scrub %> |
<%= link_to 'Back', scrubs_path %>

app/views/scrubs/index.html.erb
<h1>Listing scrubs</h1>
<br>
<table>
  <thead>
    <tr class="name_title">
      <th>Name</th>
      <th>File type</th>
      <th>Size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
  <% cache ['scrub', Scrub.latest] do %>
    <% @scrubs.each do |scrub| %>
      <% cache ['entry', scrub] do %>
        <div class="entry">
          <tr class="<%= cycle('list_line_odd', 'list_line_even')%>">
            <td> <h3><%= scrub.name %></h3> </td>
            <td> <h2><%= scrub.file_type %></h2></td>
            <td> <num><%= scrub.size %></num></td>
            <td class="list_actions">
              <%= link_to 'Show', scrub %><br/>
              <%= link_to 'Edit', edit_scrub_path(scrub) %><br/>
              <%= link_to 'Destroy', scrub, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        </div>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scrub', new_scrub_path %>

app/views/scrubs/new.html.erb
<h1>New scrub</h1>

<%= render 'form' %>

<%= link_to 'Back', scrubs_path %>

app/views/scrubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scrub.name %>
</p>

<p>
  <strong>File type:</strong>
  <%= @scrub.file_type %>
</p>

<p>
  <strong>Size:</strong>
  <%= @scrub.size %>
</p>

<%= link_to 'Edit', edit_scrub_path(@scrub) %> |
<%= link_to 'Back', scrubs_path %>

app/views/users/_form.html.erb
<div class="yafu_form">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <fieldset>
  <legend>Input entry about user</legend>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :d_birth %><br>
    <%= f.date_select :d_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>
<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Email</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>D birth</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.d_birth %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>D birth:</strong>
  <%= @user.d_birth %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>